export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_FAILED = 'MOVIES_FAILED';
export const ADD_MOVIES = 'ADD_MOVIES';

export const MOVIE_LOADING = 'MOVIE_LOADING';
export const MOVIE_FAILED = 'MOVIE_FAILED';
export const ADD_MOVIE = 'ADD_MOVIE';

export const ORDERS_LOADING = 'ORDERS_LOADING';
export const ORDERS_FAILED = 'ORDERS_FAILED';
export const ADD_ORDERS = 'ADD_ORDERS';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';

export const MOVIE_CINEMA_SELECTED = 'MOVIE_CINEMA_SELECTED';
export const MOVIE_DATE_SELECTED = 'MOVIE_DATE_SELECTED';
export const MOVIE_TIME_SELECTED = 'MOVIE_TIME_SELECTED';
export const MOVIE_SEATS_SELECTED = 'MOVIE_SEATS_SELECTED';
export const MOVIE_SEATS_REMOVED = 'MOVIE_SEATS_REMOVED';

export const ORDER_SAVING = 'ORDER_SAVING';
export const ORDER_SAVE_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_SAVE_FAILED = 'ORDER_FAILED';

export const ORDER_SUBMITING = 'ORDER_SUBMITING';
export const ORDER_SUBMITING_SUCCESS = 'ORDER_SUBMITING_SUCCESS';
export const ORDER_SUBMITING_FAILED = 'ORDER_SUBMITING_FAILED';
